version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  job_build:
    environment:
      DOCKER_IMAGE: mailnophone03/phpfpm
      DOCKER_TAG: latest
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - run:
          name: Push image to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE:$DOCKER_TAG
workflows:
  my-pipeline:
    jobs:
      - job_build
